AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for ECS task's Project figtree
Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: figtreeTaskRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: figtreelogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:logs:us-east-2:502937263541:log-group:figtree:*
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: figtreeCredentials
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:secretsmanager:us-east-2:502937263541:secret:figtree-*
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
Outputs:
  TaskRoleArn:
    Value: !Ref TaskRole
    Description: ARN of Task Role
